### ISSUE TITLE
Checking for customer id in the config

### ISSUE THREAD

**Issue by ashishmgupta** [TeleSign/csharp_telesign#11]
I won't say Its an issue - but I dont know how and where to put comments. Just a question If this was intentional not to check for the customer id as well?
## csharp_telesign-master\csharp_telesign-master\src\TeleSign.Services\TeleSignService.cs

if (string.IsNullOrEmpty(this.configuration.Credential.SecretKey))
            {
                throw new ArgumentException("No secret key was provided. Requests to TeleSign services require require a valid customer id and secret key.");
            }

Shouldn't the constructor for "TeleSignCredential" checks for null customer id as well?

/// <summary>

        /// Initializes a new instance of the TeleSignCredential class.
        /// </summary>

        /// <param name="customerId">The customer id.</param>
        /// <param name="secretKey">The customers secret key.</param>
        public TeleSignCredential(
                    Guid customerId,
                    string secretKey)
        {
            CheckArgument.NotNullOrEmpty(secretKey, "secretKey");
            CheckArgument.NotNullOrEmpty(customerId, "customerId"); // ADDED
            this.CustomerId = customerId;
            this.SecretKey = secretKey;
        }

**Comment by ramsay** [comment]
This is for a deprecated version of the SDK.
