### ISSUE TITLE
publish a nuget package for this library

### ISSUE THREAD

**Issue by brphelps** [TeleSign/csharp_telesign#16]
Any chance you could publish a nuget package for this? This would enable easy consumption in .NET code.

**Comment by ammaraltahan** [comment]
It would definitely help to have a NuGet package. We ended up creating our own CI build for this SDK, packaged it ourselves into a NuGet and deployed it to our internal repository.

**Comment by Maverick-JM** [comment]
Considering how trivial it is to publish to nuget, it's actually kindof mind-boggling this *isn't* on nuget already. I've published it to our internal nuget as that's pretty much the only sensible way to use this :).

**Comment by jarradsl** [comment]
Resolved with 2.x release. Available [here](https://www.nuget.org/packages/Telesign/).
