### ISSUE TITLE
c# SDK generates the "verification" code even if the consumer omits it

### ISSUE THREAD

**Issue by ammaraltahan** [TeleSign/csharp_telesign#17]
It is mentioned numerous times in the documentation that it is a best practice to let Telesign generate the code as it is more secure, but looking at the c# code (SDK) that consumes the REST Api, even if we omit passing the verification code, the c# code detects that there is no code passed so it generate one using Random class and then passes it to the REST api, so technically there is no way to let the REST API generate the code for us.

Here is where the SDK generate the code:
https://github.com/TeleSign/csharp_telesign/blob/master/src/TeleSign.Services.Verify/RawVerifyService.cs#L359

```
private static Dictionary<string, string> ConstructVerifyArgs(
                    VerificationMethod verificationMethod, 
                    string phoneNumber, 
                    string verifyCode, 
                    string messageTemplate, 
                    string language,
                    string validityPeriod = null,
                    string useCaseId = RawVerifyService.DefaultUseCaseId)
        {
            // TODO: Review code generation rules.
            if (verifyCode == null)
            {
                Random r = new Random();
                verifyCode = r.Next(100, 99999).ToString();
            }
            else
            {
                if (verificationMethod == VerificationMethod.TwoWaySms)
                {
                    throw new ArgumentException("Verify Code cannot be specified for Two-Way SMS", "verifyCode");
                }
            }
```

**Comment by jarradsl** [comment]
Resolved with 2.x release.
