### ISSUE TITLE
No way to verify valid code with Telesign SDK

### ISSUE THREAD

**Issue by ammaraltahan** [TeleSign/csharp_telesign#23]
We started looking into upgrading our Telesign SDK to the latest version, I downloaded the latest, and I've noticed that there is no way telesign can generate a code, nor a way to ask telesign to verify the code.

We are an enterprise client, and we are in production right now with Telesign SDK V 1.0.  if we consume V2.0 means we have to significantly change our integration to start generating the code and verify it ourselves.

Can someone please clarify, how we're supposed to call telesign api to verify a code when upgrading from V1.0 to V2.0?

**Comment by d0minicr** [comment]
Sorry for the confusion.  Our enterprise SDK is currently a private Github repo.  In our enterprise SDK, we will continue to generate the verify code for you.  The SDK you are using is for a generic text-to-speech solution and is not tailored for 2FA.  

Please send an email to your TeleSign account manager and they will grant you access to the enterprise SDK.
